Fix: clippy errors in eth-connector (#32)
Clippy reports many errors like the following:

```
error: use of `expect` followed by a function call
   --> src/prover.rs:143:14
    |
143 |             .expect(str_from_slice(FAILED_PARSE));
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| { panic!("{}", str_from_slice(FAILED_PARSE).to_string()) })`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call
```

This commit corrects all those errors by using a new trait on Option and Result that can take an expect message in bytes.